name: Cleanup Failed Runs

on:
  workflow_dispatch:

permissions:
  actions: write  # allow deleting workflow runs

jobs:
  cleanup_failed:
    runs-on: ubuntu-latest
    steps:
      - name: Delete failed workflow runs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            // Fetch up to 100 most recent completed runs
            const response = await github.rest.actions.listWorkflowRunsForRepo({
              owner,
              repo,
              status: 'completed',
              per_page: 100
            });
            // Only keep runs that actually failed
            const failedRuns = response.data.workflow_runs.filter(run => run.conclusion === 'failure');
            if (failedRuns.length === 0) {
              console.log('No failed workflow runs found.');
            } else {
              for (const run of failedRuns) {
                console.log(`Deleting failed run id=${run.id}, name=${run.name}`);
                await github.rest.actions.deleteWorkflowRun({ owner, repo, run_id: run.id });
              }
            }